config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get 'pages/home' , to: 'pages#home'
  
  resources :companies do
  	resources :positions
    collection do
      get 'search'
    end

  end

  resources :companies do
    resources :internal_levels

  end

  resources :positions do
  	collection do
  		get 'search'
      get :autocomplete 
  	end
    member do
      get :reporting, :reporters
    end
  end


  #resources :users do
    #resources :profiles
 # end
  
  resources :profiles
  
  get '/users/:user_id/profile', to: 'profiles#edit'
  post '/users/:user_id/profile', to: 'profiles#update'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :users do 
    collection do
      post 'update_multiple'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :relationships,       only: [:create, :destroy]
  
  get '/auth/:provider/callback', to: 'oauths#create'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'
  
  #resources :positions

  #get '/companies', to: 'companies#index'
  
  #get '/companies/new', to: 'companies#new', as: 'new_company'
  #get '/companies/:id', to: 'companies#show', as: 'company'
  #post '/companies', to: 'companies#create'
end

app/models/position.rb
class Position < ApplicationRecord
	validates :title, presence: true, length: {maximum: 50}
	validates :title, uniqueness: { scope: :company,
    message: "Already exists!!" , case_sensitive: false}
	#validates :description, presence: true , length: {minimum: 30, maximum: 1000}
	#validates :job_expectation, presence: true, length: {minimum: 30, maximum: 1000}
	#validates :avg_yrs_exp, presence: true
	#validates :criteria_for_next_level, presence: true, length: {minimum: 30, maximum: 1000}

	has_many :bands
	has_many :internal_levels, through: :bands
	#has_many :companies, through: :internal_levels
	belongs_to :company

	#defines the org/reporting structure
	has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "reporter_id",
                                  dependent:   :destroy 

    has_many :reporting, through: :active_relationships, source: :reported

    has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "reported_id",
                                   dependent:   :destroy

    has_many :reporters, through: :passive_relationships, source: :reporter
    has_many :profiles

	searchkick word_start: [:title]
	scope :search_import, -> { includes(:company, :internal_levels) }
	after_commit :reindex_position

	  def reindex_position
	    Position.reindex # or reindex_async
	  end
	

	def search_data
	    attributes.merge(
	      title: title,
	      company_name: company.try(:name),
	      company_id: company.try(:id),
	      description: description,
	      internal_levels: "#{internal_levels.map(&:name).join(" ")}"
	    )
	end

	# Follows a user.
  def report(other_position)
    reporting << other_position
  end

  # Unfollows a user.
  def unreport(other_position)
    reporting.delete(other_position)
  end

  # Returns true if the current user is following the other user.
  def reporting?(other_position)
    reporting.include?(other_position)
  end

end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
	
	before_action :set_company, only: [:create, :update, :new, :edit]
	before_action :set_position, only: [:update, :edit]
	

	def index
		if params[:term]
			if Rails.env.production?
				@titles = Position.select("distinct title").where("title ILIKE ?", "%#{params[:term]}%").order(:title)
			else
				@titles = Position.select("distinct title").where("title like ?", "%#{params[:term]}%").order(:title)
			end
    		render json: @titles.map(&:title)
    	end

    	
  	end
	

	def search
		if params[:search_company].present? && params[:search_position].present?

			#@company = Company.find_by_name(params[:search_company])
			@company = Company.where('lower(name)= ?', params[:search_company].downcase).first

			#query = Company.joins(:positions).where('positions.title' => params[:search_position]) 
			if !@company.nil?
				@results = Position.search(params[:search_position], fields: [:title], match: :word_start, load: false, where: {company_id: @company.id})
				puts @results.size
				position = @results.first
				@results.each do |position|
					puts position.title
  					puts position.company_name
  					puts position.internal_levels

				end
				if @results.size ==0
					flash.now[:warning] = "We don't have data for this position currently."
				return
			end
			else
				flash.now[:warning] = "Search returned 0 results."
				return
			end
			
		elsif params[:search_company].present? && !params[:search_position].present?
			@company = Company.where('lower(name)= ?', params[:search_company].downcase).first
			puts "ONLY COMPANY NO POSITION"
			if @company.nil?
				flash.now[:warning] = "Search returned 0 results."
				return
			end
			
		else
			puts "NO COMPANY OR POSITION PROVIDED FOR SEARCH"
			flash.now[:error] = "Search returned 0 results."
			#redirect_to root_url

		end
	end

	def autocomplete
    render json: Position.search(params[:search_position], {
      fields: ["title^5"],
      match: :word_start,
      limit: 10,
      load: false,
      misspellings: {below: 5}
    }).map do |position|
    	{title: position.title, value: position.id}
    end
  end



	def new
		@position = Position.new
	end

	def create

		puts params[:position][:internal_level_ids]

		@position = @company.positions.build(position_params)
		if @position.save
			flash[:success] = "Position saved successfully."
			redirect_to company_path(@company)
		else
			flash[:danger] = "Position did not save."
			render 'new'
		end
		#@position.internal_level_ids << params[:position][:internal_level_ids]
		#@position.save
		#@position.internal_levels << @internal_level
		
		

	end

	def create_old
		Position.transaction do
			Company.transaction do
				@position = Position.new(position_params)
				if @position.save
					@company = @company.internal_levels.new(position: @position, name: params[:internal_level][:name])
						if @company.save
							flash[:success] ="Position was created successfully"
							redirect_to company_path(@company)
						else
							raise 'Position did not save'
							render 'new'
						end
				else
					raise 'Position did not save'
					flash[:error] = "Position did not save"
					render 'new'
				end
				

			end
		end
	end

	def edit
		
	end

	def update
		if @position.update(position_params)
			flash[:success] = "This position was updated successfully."
			redirect_to company_path(@company)
		else
			render 'edit'
		end
	end

	private

	def set_position
		@position = Position.find(params[:id])
	end
	
	def set_company
		@company = Company.find(params[:company_id])
	end


	def position_params
		params.require(:position).permit(:title, :description, :job_expectation, :avg_yrs_exp, :criteria_for_next_level, internal_level_ids: [])
	end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
			<div class="login login1">
				<%= form_for([@company,@position], :html => {class: "form-horizontal", role: "form"}) do |f| %>
					<div class="form_row form_row1">
						<div class="form_label">Position/Job Title</div>
						<div class="form_element"><%= f.text_field :title, 
                                    placeholder: "Position/Title" %></div>
						<div class="clearfix"></div>
					</div>
					<div class="form_row form_row1">
					<div class="form_label">Internal level</div>
					<div class="form_element"> 
						<% @company.internal_levels.each do |l| %>
						  <%= check_box_tag "position[internal_level_ids][]", l.id, @position.internal_level_ids.include?(l.id) %>
						  <%= l.name %><br>
						<% end %>
					</div>
					<div class="clearfix"></div>
					</div>
					
					
					<div class="form_row  form_row1">
					<div class="form_label">Average Years of career exerience required at this level?</div>
					<div class="form_element"><%= f.text_field :avg_yrs_exp, 
                                    placeholder: "Avg years of experience" %></div>
					<div class="clearfix"></div>
					</div>
					
					<div class="form_row form_row1">
					<div class="form_label">job desc</div>
					<div class="form_element"><%= f.text_area :description, 
                                    placeholder: "job description" %></div>
					<div class="clearfix"></div>
					</div>
					<div class="form_row form_row1">
					<div class="form_label">Job Expectation</div>
					<div class="form_element"><%= f.text_area :job_expectation, 
                                    placeholder: "job expectation" %></div>
					<div class="clearfix"></div>
					</div>
					<div class="form_row form_row1">
					<div class="form_label">Criteria for next level</div>
					<div class="form_element"><%= f.text_area :criteria_for_next_level,
                                    placeholder: "Critera for next level" %></div>
					<div class="clearfix"></div>
					</div>
					
					<div class="bottom_btns1">
						<div class="cancel cancel1"><%= link_to "Cancel", company_path(@company) %> </div>
						<%= f.submit class: " btn btn-green edit1" %>
					
						<div class="clearfix"></div>
					</div>
				<%end%>
				<div class="clearfix"></div>
					</div>
					<div class="clearfix"></div>
					</div>
			</div>
			
			
		
			
	

app/views/positions/edit.html.erb
<%= render 'shared/errors', object: @position %>
<div class="login_form">
	<h2 class="signin update1">Update Your Position</h2>
	<%= render 'form' %>
</div>

app/views/positions/new.html.erb
<%= render 'shared/errors', object: @position %>
<div class="login_form">
	<h2 class="signin update1">Create New Position</h2>
	<%= render 'form' %>
</div>

app/views/positions/search.html.erb
<div class="infomation">
  <div class="fillDetails filldetails1">
  <div class="container">
  <%= form_tag search_positions_path, method: :get do %>
    <div class="form_row">
      <div class="form_element">

          
            <%= text_field_tag :search_company, params[:search_company], data: { autocomplete_source: companies_path}, required: :true, class: "text-box text-box2", placeholder: "Company Name" %>
              
            <%= text_field_tag :search_position, params[:search_position], class: "text-box1 text-box3",
             placeholder: "Position/Title", data: { autocomplete_source: positions_path}%>
      <%= submit_tag "Search", name: nil, class: " btn btn-green btn-search"%>
            
          </div>
          <div class="clearfix"></div>
        </div>
        <% end %>
        <%= render 'layouts/messages' %>
  </div>
  </div>
    <div class="container">
      <% if !@company.nil? %>
        <div class="company_info">
          <div class="company_logo"><%= image_tag @company.picture.url if @company.picture? %></div>
          <div class="company_name"><%= link_to @company.name%></div>
          <div class="clearfix"></div>
        </div>
      <% end %>
      <% if !@results.nil? && @results.size > 0%>
        <div class="Section1">
          <div class="col-md-12 nopadding">
            <div class="col-md-6 nopadding">
              <div class="jobInfo">
                <div class="googleAdds1">
                  <div class="ads profile_level"> 
                      <div class="Ads_heading">Business Title</div>
                      <div class="Ads_Data"><%= @results[0].title %></div>
                       <div class="clearfix"></div>
                    </div>
                    <div class="ads profile_level" style="margin-left: 2%;"> 
          
                       <div class="Ads_heading">Job profile Level</div>
                       <div class="Ads_Data"><%= @results[0].internal_levels %></div>
                       <div class="clearfix"></div>
                    </div>
                    <div class="ads jobdesc"> 
                    <div class="Ads_heading">Typical Job Desc</div>
                    <div class="Ads_Data"><%= @results[0].description %></div>
                      
                    <div class="clearfix"></div>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </div>
            </div>
            <div class="col-md-6 rightPadding">
            <div class="comingsoon">Coming Soon</div>
              <div class="ads orgChart">
                <div class="tree">
                  <ul>
                    <li> <a href="#">Parent</a>
                      <ul>
                        <li> <a href="#">Child</a>
                          <ul class="grand-child">
                            <li><a href="#">Grand Child</a></li>
                            <li> <a href="#">Grand Child</a> </li>
                            <li><a href="#">Grand Child</a></li>
                            <li><a href="#">Grand Child</a></li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="clearfix"></div>
        </div>
        <% else %>
        <div class="HowItWorks">
          <% if !@company.nil? %>
            <div class="ads">
                <% @PositionPaginator = @company.positions.paginate(:page => params[:page], :per_page => 5) %>
                <% @PositionPaginator.each do |p| %>
                <div class="listing">
                  <h3 class="heading"><%= p.title %></h3>
                  <p class="heading-content"><%= p.description %></p>
                  <div class="clearfix"></div>
                </div>
                <% end %>
                <div class="clearfix"></div>
            </div>
            <%= will_paginate @PositionPaginator %>
          <% end %>
        </div>
        
    <% end %>
    <div class="HowItWorks">
        <div class="col-md-12 nopadding">
         <!--  <h2>Similar Position Company Name(option-1)</h2> -->
          <div class="col-sm-3 col-md-3 nopadding">
            <div class="ads ads1">
              
              <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="col-sm-3 col-md-3 nopadding">
            <div class="ads ads1">
              
              <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="col-sm-3 col-md-3 nopadding">
            <div class="ads ads1">
             
              <div class="clearfix"></div>
            </div>
          </div>
          <div class="col-sm-3 col-md-3 nopadding">
            <div class="ads ads1">
              
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
        
    </div>
  </div>
   <div class="clearfix"></div>