config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get 'pages/home' , to: 'pages#home'
  
  resources :companies do
  	resources :positions
    collection do
      get 'search'
    end

  end

  resources :companies do
    resources :internal_levels

  end

  resources :positions do
  	collection do
  		get 'search'
      get :autocomplete 
  	end
    member do
      get :reporting, :reporters
    end
  end


  #resources :users do
    #resources :profiles
 # end
  
  resources :profiles
  
  get '/users/:user_id/profile', to: 'profiles#edit'
  post '/users/:user_id/profile', to: 'profiles#update'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :users do 
    collection do
      post 'update_multiple'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :relationships,       only: [:create, :destroy]
  
  get '/auth/:provider/callback', to: 'oauths#create'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'
  
  #resources :positions

  #get '/companies', to: 'companies#index'
  
  #get '/companies/new', to: 'companies#new', as: 'new_company'
  #get '/companies/:id', to: 'companies#show', as: 'company'
  #post '/companies', to: 'companies#create'
end

app/models/internal_level.rb
class InternalLevel < ApplicationRecord
  belongs_to :company
  has_many :bands , dependent: :destroy
  has_many :positions, through: :bands
 # validates :name, presence: :true, uniqueness: { case_sensitive: false }
end

app/controllers/internal_levels_controller.rb
class InternalLevelsController < ApplicationController
	before_action :set_company

	def new
		@level = InternalLevel.new
	end

	def create
		@level = @company.internal_levels.new(level_params)
		if @level.save
      		flash[:success] = "Successfully created #{@level.name}"
      		#@company.internal_levels
      		redirect_to new_company_internal_level_path(@company)
		else
			render 'new'
		end
	end

	def destroy
		@company.internal_levels.find(params[:id]).destroy
		#@company = InternalLevel.find(params[:id]).destroy
		flash[:success] = "Level deleted successfully !"
		redirect_to new_company_internal_level_path(@company)

	end

	private
	def set_company
		@company = Company.find(params[:company_id])
	end

	def level_params
		params.require(:internal_level).permit(:name)
	end

end

app/views/internal_levels/_form.html.erb
<%= form_for([@company, @level], url:company_internal_levels_url) do |f| %>
  <%= render 'shared/errors', object: @level %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/internal_levels/_levels.html.erb
<table class="table table-striped">
  <tr>
  	
    <th>Internal Level</th>
    
    <th>Actions</th>
  </tr>
 
  <% @company.internal_levels.each do |l| %>
    <tr>
      
      <td><%= l.name %></td>
      
      <td><%= link_to 'Delete', company_internal_level_path(@company, l), class: "btn btn-xs btn-warning", 
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/internal_levels/edit.html.erb
<%= render 'shared/page_title', title: "Edit Level"%>
<%= render 'form' %>

app/views/internal_levels/new.html.erb
<%= link_to 'Back to Company Page', company_path(@company), class: "btn btn-primary" %>

<% provide(:button_text, 'Create a level') %>
<%= render 'shared/page_title', title: "Internal Levels for #{@company.name}"%>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>



<div class="levels">
	<div class="row">
	  <div class="col-md-6 col-md-offset-3">
	    <%= render 'levels' %>
	  </div>
	</div>
</div>