config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get 'pages/home' , to: 'pages#home'
  
  resources :companies do
  	resources :positions
    collection do
      get 'search'
    end

  end

  resources :companies do
    resources :internal_levels

  end

  resources :positions do
  	collection do
  		get 'search'
      get :autocomplete 
  	end
    member do
      get :reporting, :reporters
    end
  end


  #resources :users do
    #resources :profiles
 # end
  
  resources :profiles
  
  get '/users/:user_id/profile', to: 'profiles#edit'
  post '/users/:user_id/profile', to: 'profiles#update'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :users do 
    collection do
      post 'update_multiple'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :relationships,       only: [:create, :destroy]
  
  get '/auth/:provider/callback', to: 'oauths#create'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'
  
  #resources :positions

  #get '/companies', to: 'companies#index'
  
  #get '/companies/new', to: 'companies#new', as: 'new_company'
  #get '/companies/:id', to: 'companies#show', as: 'company'
  #post '/companies', to: 'companies#create'
end

app/models/company.rb
class Company < ApplicationRecord

	validates :name, presence: true, uniqueness: { case_sensitive: false }
	#validates :company_type, presence: true
	mount_uploader :picture, PictureUploader
	has_many :internal_levels, dependent: :destroy
	#has_many :positions, through: :internal_levels
	validate  :picture_size
	has_many :positions, dependent: :destroy
	has_many :profiles
	searchkick 
	scope :ci_find, lambda { |attribute, value| where("lower(#{attribute}) = ?", value.downcase).first }
	
	

	private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

	before_action :set_company, only: [:show, :edit, :update]
	#def index
	#	@companies = Company.all
	#end

	def index
		if params[:term]
			#needed for case insensitive search
			if Rails.env.production?
				@companies = Company.order(:name).where("name ILIKE ?", "%#{params[:term]}%")
			else
				@companies = Company.order(:name).where("name like ?", "%#{params[:term]}%")
			end
    		render json: @companies.map(&:name)

    	else
    		@companies = Company.paginate(page: params[:page], per_page: 10)
    		
    	end

  	end
	
	def show
		
	end



	def search
		if params[:search_company].present?
			@companies= Company.search params[:search_company], fields: [:name]
			render 'index'
		else
			@companies = Company.paginate(page: params[:page], per_page: 10)

		end
	end

		

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_params)
		if @company.save
			flash[:success] ="Company was created successfully"
			redirect_to company_path(@company)
		else
			render 'new'
		end
				
	end

	#submits to update
	def edit
		
	
	end

	def update
		if @company.update(company_params)
			flash[:success] = "Company was updated successfully!"
			redirect_to company_path(@company)
		else
			render 'edit'
		end
	end

	def destroy
		@company = Company.find(params[:id]).destroy
		flash[:success] = "Company delete successfully !"
		redirect_to companies_path

	end

	private

	def set_company
		@company = Company.find(params[:id])
	end

	def company_params
		params.require(:company).permit(:name, :company_type, :picture, :location, :industry)
	end
end

app/views/companies/_form.html.erb
<%= render 'shared/errors', object: @company %>
<div class="row">
	<div class="col-md-12">
		<%= form_for(@company, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-md-2">
				<%= f.label :name %>

				</div>
				<div class="col-md-8">
					<%= f.text_field :name, class: "form-control", placeholder: "Company name", autofocus: true%>	
				</div>

			</div>	
			<div class="form-group">
				<div class="control-label col-md-2">
				<%= f.label :company_type%>
				</div>
				<div class="col-md-8">
         			 <%= f.text_area :company_type, rows: 10, class: "form-control", 
                                    placeholder: "Private or Public" %>
        		</div>
			</div>
			<div class="form-group">
				<div class="control-label col-md-2">
					<%= f.label "Upload company logo"%>
				</div>
				<div class="col-md-8">
					<span class="picture">
			    		<%= f.file_field :picture , accept: 'image/jpeg,image/gif,image/png'%>
			  		</span>
			  	</div>
			 </div>
			<div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>

        </div>
      </div>
		<% end %>
		<div class="col-md-4 col-md-offset-4 colormatch">
     		 [ <%= link_to "Cancel request and return to Companies listing", companies_path %> ]
    </div>
	</div>
</div>

<script type="text/javascript">
  $('#company_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/companies/edit.html.erb
<%= render 'shared/page_title', title: "Edit an existing company"%>
<%= render 'form' %>

app/views/companies/index.html.erb
  <div class="infomation">
    <div class="container">
      
      <div class="section-heading" style="padding-bottom:0px;">
      <h1 class="pull-left">Companies</h1>
      <div class="pull-right">
      
      <%= link_to 'Add company', new_company_path, class:" btn btn-green" %>
      </div>
        <div class="clearfix"></div>
      </div>
      <div class="dashboard-row ads" style="margin:10px 0px;">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th style="text-align: center;">Company Logo</th>
              <th style="text-align: center;">Company Name</th>
              <th style="text-align: center;">type</th>
              <th style="text-align: center;">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @companies.each do |company| %>
              <tr>
                <td><div class="companyLogoPic"><%= image_tag(company.picture.url(:thumb).to_s) if company.picture? %> </div></td>
                <td><%= company.name %></td>
                <td><%= company.company_type %></td>
                <td>
                  <%= link_to company_path(company) do %>
                      <%= fa_icon "eye", class: "action-btn" , aria: {hidden: true} %>
                  <% end %>
                  <%= link_to edit_company_path(company) do %>
                      <%= fa_icon "pencil", class: "action-btn" , aria: {hidden: true} %>
                  <% end %>
                  <%= link_to company_path(company), method: :delete, data: { confirm: 'Are you sure?' }  do %>
                      <%= fa_icon "trash-o", class: "action-btn" , aria: {hidden: true} %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            
          </tbody>
        </table>
        <%= will_paginate @companies %>
        <div class="clearfix"></div>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="clearfix"></div>
  <div class="push"></div>

app/views/companies/new.html.erb
<%= render 'shared/page_title', title: "create a new company"%>
<%= render 'form' %>

app/views/companies/show.html.erb
<div class="infomation">
    <div class="container">
     
      <div class="dashboard-row ads" style="margin:10px 0px;">
			<div class="">
			<div class="col-md-3">
			<div class="form_row">
				<div class="form_element" style="">
					<span class="upload_file">
						<div class="company_image">
							<%= image_tag @company.picture.url if @company.picture? %>
						</div>
					</span>
				</div>
				<div class="clearfix"></div>
			</div>
			
			</div>
			<div class="col-md-9">
			<div class="">
				<form>
					<div class="form_row">
						 <h1 class="pull-left"><%= @company.name %></h1>
						 <div class="clearfix"></div>
					</div>
					 <div class="clearfix"></div>
					<div class="form_row">
						<%= link_to "Edit", edit_company_path(@company), class: "  btn btn-green btn-search pull-left"%>
					
					</div>
				</form>
			</div>
			</div>
			
		
			
		</div>
       
        <div class="clearfix"></div>
      </div>
    </div>
    <div class="clearfix"></div>
</div>

<div class="infomation">

    <div class="container">
    <%= render 'layouts/messages' %>
      <div class="section-heading" style="padding-bottom:0px;">
        <h1 class="pull-left">Positions</h1>
        <div class="pull-right">
        	<%= link_to 'Add Position', new_company_position_path(@company), class: " btn btn-green btn-search add-position" %>
		 	<%= link_to 'Add Level', new_company_internal_level_path(@company), class: "btn btn-green btn-search" %>
		 
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="dashboard-row ads" style="margin:10px 0px;">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th style="text-align:center;">Title</th>
              <th style="text-align:left;width:5%;">Internal Level</th>
              <th style="text-align: center;">Description</th>
              <th style="text-align: center;width:20%;">Job Expectation</th>
			  <th style="text-align: center;width:12%;">Average years of experience</th>
			  <th style="text-align: center;width:10%;">Criteria for next level</th>
			  <th style="text-align: center; width:10%;">Action</th>
			  
            </tr>
          </thead>
          <tbody>
          <% @PositionPaginator = @company.positions.paginate(:page => params[:page], :per_page => 5) %>
          	<% @PositionPaginator.each do |p| %>
	            <tr>
	               <td style="text-align: left;"><%= p.title %></td>
					<td style="text-align: left;">
						<% p.internal_levels.each do |l| %>
							<%= l.name %>
						<% end %>	
					</td>
	              <td><%= p.description %></td>
				  <td style="text-align: left;"><%= p.job_expectation %></td>
					<td style="text-align: left;"><%= p.avg_yrs_exp %></td>
	              <td><%= p.criteria_for_next_level %></td>
	              <td>
	              	<%= link_to edit_company_position_path(@company, p) do %>
                    	<%= fa_icon "pencil", class: "action-btn" , aria: {hidden: true} %>
                  	<% end %>
                  	<%= link_to position_path(p), method: :delete, data: { confirm: 'Are you sure?' }  do %>
                      <%= fa_icon "trash-o", class: "action-btn" , aria: {hidden: true} %>
                  	<% end %>

	              </td>
	            </tr>
           	<% end %>
           
           
           
          </tbody>
        </table>
        <%= will_paginate @PositionPaginator %>
        <div class="clearfix"></div>
      </div>
    </div>
    <div class="clearfix"></div>
</div>