config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get 'pages/home' , to: 'pages#home'
  
  resources :companies do
  	resources :positions
    collection do
      get 'search'
    end

  end

  resources :companies do
    resources :internal_levels

  end

  resources :positions do
  	collection do
  		get 'search'
      get :autocomplete 
  	end
    member do
      get :reporting, :reporters
    end
  end


  #resources :users do
    #resources :profiles
 # end
  
  resources :profiles
  
  get '/users/:user_id/profile', to: 'profiles#edit'
  post '/users/:user_id/profile', to: 'profiles#update'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :users do 
    collection do
      post 'update_multiple'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :relationships,       only: [:create, :destroy]
  
  get '/auth/:provider/callback', to: 'oauths#create'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'
  
  #resources :positions

  #get '/companies', to: 'companies#index'
  
  #get '/companies/new', to: 'companies#new', as: 'new_company'
  #get '/companies/:id', to: 'companies#show', as: 'company'
  #post '/companies', to: 'companies#create'
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container1">
    <div class="footer_col"> </div>
    <div class="footer_col pull-right text-center copyright"></div>
    <div class="footer_col text-center footer_icon">
					<a href=""><span class="facebook"></span></a>
					<a href=""><span class="twitter"></span></a>
					<a href=""><span class="youtube"></span></a>
					<a href=""><span class="linked-in"></span></a>
                  <!--<a href=""><span><i class="fa fa-facebook" aria-hidden="true"></i></span></a>
                    <a href=""><span><i class="fa fa-twitter" aria-hidden="true"></i></span></a>
                    <a href=""><span><i class="fa fa-youtube-play" aria-hidden="true"></i></span></a>
					<a href=""><span><i class="fa fa-linkedin" aria-hidden="true"></i></span></a> -->
                    <div class="clearfix"></div>
	</div>
	
    <div class="clearfix"></div>
  </div>
</div>

app/views/layouts/_messages.html.erb
		<% flash.each do |name, msg| %>
      		<div class="alert alert-<%= name %>">
      			<a href="#" class="close" data-dismiss="alert">&#215;</a>
      			<%= msg %>
      		</div>
      		
    	<%end%>

app/views/layouts/_navigation.html.erb
<div class="header1" id="header"><!--header section starts from here-->
    <div class="container1 container768">
      <div class="logo_section"><%= link_to image_tag('logo.PNG'), root_path, id: "logo"%></div>

      <div class="menuIcon"><%= image_tag "menuicon.png", class: "icon" %></div>
      <div class="headermenu">
        <ul class="headermenulist inner_page" id="nav">
          
          <li><%= link_to "Home", root_path %></li>

          <% if logged_in? %>
            <% if current_user.admin? %>
              <li><%= link_to "Companies", companies_path%></li>
              <li><%= link_to "Users", users_path %></li>
            <% end %>
            
            <li class="hsubs">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%=current_user.name%> <b class="caret"></b>
            </a>
            <ul class="subs">
              <li><%= link_to "Profile", "/users/#{current_user.id}/profile" %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>

        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
      <div class="clearfix"></div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Companyinsights</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	
    
  	<div class="wrapper">
    
    <%= render 'layouts/navigation' %>
    
    	<%= yield %>
    
      
      
    </div>
    <div class="push"></div>
    <%= render 'layouts/footer' %>

  </body>
</html>